### ISSUE TITLE
FunctionClauseError for some images

### ISSUE THREAD

**Issue by nico-amsterdam** [am-kantox/exexif#7]
I got this error when running Exexif.exif_from_jpeg_file for the attached image:

** (FunctionClauseError) no function clause matching in Exexif.Decode.orientation/1    
    
    The following arguments were given to Exexif.Decode.orientation/1:
    
        # 1
        0
    
    Attempted function clauses (showing 8 out of 8):
    
        defp orientation(1)
        defp orientation(2)
        defp orientation(3)
        defp orientation(4)
        defp orientation(5)
        defp orientation(6)
        defp orientation(7)
        defp orientation(8)
    
    (nextexif 0.1.2) lib/exexif/decode.ex:103: Exexif.Decode.orientation/1
    (nextexif 0.1.2) lib/exexif/decode.ex:13: Exexif.Decode.tag/3
    (nextexif 0.1.2) lib/exexif.ex:111: Exexif.read_tags/5
    (nextexif 0.1.2) lib/exexif.ex:67: Exexif.read_exif/1

![IMG_20210619_102957](https://github.com/user-attachments/assets/f319ec6f-519a-465a-a476-0f3b27954a32)

**Comment by speeddragon** [comment]
A bit late, but this is weird because since cd9c53823a13163de8dee733bd0bfb712f788256 this is set as `Unknown (0)`. Check if you are using the latest version (`{:nextexif, "~> 0.1.2"}`).

**Comment by nico-amsterdam** [comment]
I was running this in Livebook and I first tried exexif. 
I guess I should have used 'Setup without cache' to clear the cache and run nextexif, because apparently it mixes the modules of nextexif with exexif.
